# Generated by Django 5.2.17 on 2026-08-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='deve_alterar_senha',
            field=models.BooleanField(default=False),
        ),
    ]
