# Generated by Django 5.2.17 on 2026-08-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'item de peça',
                'verbose_name_plural': 'itens de peça',
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'peça',
                'verbose_name_plural': 'peças',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='RequisicaoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'requisição de peça',
                'verbose_name_plural': 'requisições de peça',
                'ordering': ('-criada_em',),
            },
        ),
    ]
