# Generated by Django 5.2.17 on 2026-08-15 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempeca',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_peca', to='oficina.ordemservico'),
        ),
        migrations.AddField(
            model_name='itempeca',
            name='peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_utilizados', to='estoque.peca'),
        ),
    ]
