# Generated by Django 5.2.17 on 2026-08-15 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0002_initial'),
        ('oficina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaopeca',
            name='mecanico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_peca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicaopeca',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_peca', to='oficina.ordemservico'),
        ),
        migrations.AddField(
            model_name='itempeca',
            name='requisicao_peca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='estoque.requisicaopeca'),
        ),
    ]
