# Generated by Django 5.2.17 on 2026-08-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='quantidade_minima',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisicaopeca',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=15),
        ),
    ]
