# Generated by Django 5.2.17 on 2026-08-16 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_peca_quantidade_minima_alter_requisicaopeca_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaopeca',
            name='decidida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicaopeca',
            name='decidida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_peca_decididas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicaopeca',
            name='peca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='estoque.peca'),
        ),
        migrations.AddField(
            model_name='requisicaopeca',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
