# Generated by Django 5.2.17 on 2026-08-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'acessório',
                'verbose_name_plural': 'acessórios',
            },
        ),
        migrations.CreateModel(
            name='Avaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'avaria',
                'verbose_name_plural': 'avarias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='EntradaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quilometragem', models.PositiveIntegerField(blank=True, null=True)),
                ('nivel_combustivel', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('registrada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'entrada de veículo',
                'verbose_name_plural': 'entradas de veículo',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='entradas/fotos/')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
            },
        ),
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'item de serviço',
                'verbose_name_plural': 'itens de serviço',
            },
        ),
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.PositiveSmallIntegerField()),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('chassi', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('cor', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'motocicleta',
                'verbose_name_plural': 'motocicletas',
                'ordering': ('placa',),
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mao_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'orçamento',
                'verbose_name_plural': 'orçamentos',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('descricao_problema', models.TextField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=25)),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ordem de serviço',
                'verbose_name_plural': 'ordens de serviço',
                'ordering': ('-aberta_em',),
            },
        ),
    ]
