# Generated by Django 5.2.17 on 2026-08-15 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaria',
            name='entrada_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avarias', to='oficina.entradaveiculo'),
        ),
        migrations.AddField(
            model_name='acessorio',
            name='entrada_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessorios', to='oficina.entradaveiculo'),
        ),
        migrations.AddField(
            model_name='foto',
            name='entrada_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='oficina.entradaveiculo'),
        ),
        migrations.AddField(
            model_name='motocicleta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motocicletas', to='oficina.cliente'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='oficina.cliente'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='motocicleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='oficina.motocicleta'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='ordem_servico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento', to='oficina.ordemservico'),
        ),
        migrations.AddField(
            model_name='itemservico',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_servico', to='oficina.ordemservico'),
        ),
        migrations.AddField(
            model_name='entradaveiculo',
            name='ordem_servico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrada_veiculo', to='oficina.ordemservico'),
        ),
    ]
