# Generated by Django 5.2.17 on 2026-08-16 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entradaveiculo',
            name='motivo_entrada',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='decidido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='decidido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_decididos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='AGUARDANDO_APROVACAO', max_length=25),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='concluida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_atribuidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_manutencao',
            field=models.CharField(choices=[('CORRETIVA', 'Corretiva'), ('PREVENTIVA', 'Preventiva')], default='CORRETIVA', max_length=15),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('AGUARDANDO_ORCAMENTO', 'Aguardando orçamento'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('EM_EXECUCAO', 'Em execução'), ('AGUARDANDO_PECAS', 'Aguardando peças'), ('CONCLUIDA', 'Concluída'), ('CONCLUIDA_NAO_APROVADA', 'Concluída - Não aprovado')], default='ABERTA', max_length=30),
        ),
        migrations.CreateModel(
            name='ItemChecklistEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('PNEU_DIANTEIRO', 'Pneu dianteiro'), ('PNEU_TRASEIRO', 'Pneu traseiro'), ('RODAS', 'Rodas'), ('FREIOS', 'Freios'), ('ILUMINACAO', 'Faróis e lanternas'), ('RETROVISORES', 'Retrovisores'), ('CARENAGENS', 'Carenagens'), ('SUSPENSAO', 'Suspensão'), ('PAINEL', 'Painel')], max_length=25)),
                ('estado', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('COM_AVARIA', 'Com avaria'), ('NAO_VERIFICADO', 'Não verificado')], max_length=20)),
                ('percentual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('entrada_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_checklist', to='oficina.entradaveiculo')),
            ],
            options={
                'verbose_name': 'item do checklist de entrada',
                'verbose_name_plural': 'itens do checklist de entrada',
                'constraints': [models.UniqueConstraint(fields=('entrada_veiculo', 'item'), name='checklist_item_unico_por_entrada')],
            },
        ),
    ]
