# Generated by Django 5.2.17 on 2026-08-16 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_requisicaopeca_decidida_em_and_more'),
        ('oficina', '0004_orcamento_emitido_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrcamentoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_previstas', to='oficina.orcamento')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_orcamento', to='estoque.peca')),
            ],
            options={
                'verbose_name': 'peça prevista no orçamento',
                'verbose_name_plural': 'peças previstas no orçamento',
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamentoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_previstos', to='oficina.orcamento')),
            ],
            options={
                'verbose_name': 'serviço previsto no orçamento',
                'verbose_name_plural': 'serviços previstos no orçamento',
            },
        ),
    ]
