# Generated by Django 5.2.17 on 2026-08-16 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0005_itemorcamentopeca_itemorcamentoservico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoStatusOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('ABERTA', 'Aberta'), ('AGUARDANDO_ORCAMENTO', 'Aguardando orçamento'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('EM_EXECUCAO', 'Em execução'), ('AGUARDANDO_PECAS', 'Aguardando peças'), ('CONCLUIDA', 'Concluída'), ('CONCLUIDA_NAO_APROVADA', 'Concluída - Não aprovado')], max_length=30)),
                ('novo_status', models.CharField(choices=[('ABERTA', 'Aberta'), ('AGUARDANDO_ORCAMENTO', 'Aguardando orçamento'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('EM_EXECUCAO', 'Em execução'), ('AGUARDANDO_PECAS', 'Aguardando peças'), ('CONCLUIDA', 'Concluída'), ('CONCLUIDA_NAO_APROVADA', 'Concluída - Não aprovado')], max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='oficina.ordemservico')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_status_ordem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'histórico de status da ordem',
                'verbose_name_plural': 'históricos de status das ordens',
                'ordering': ('-criado_em', '-id'),
            },
        ),
    ]
